app1/urls.py
from django.urls import path
from app1.views import *
app_name='app1'
urlpatterns=[
    path('nag/',nag,name='nag'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'
urlpatterns=[
    path('Mounika/',Mounika,name='Mounika'),
]

project12/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),

]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

def nag(request):
    return render(request,'nag.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def Mounika(request):
    return render(request,'Mounika.html')

templates/Mounika.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>I love Bangalore</h1>
       <h1> <a href="{% url 'app1:nag' %}">this is url navigation for nag</a></h1>
    </center>
    
</body>
</html>

templates/nag.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>good night bangalore</h1>
        <h1> <a href="{% url 'app2:Mounika' %}">this is url navigation for Mounika</a></h1>
    </center>
    
</body>
</html>